## YAML Template.
---
spring:
    application:
        name: zipkin-service    
server:
  port: 9411

eureka:
  instance:
      instanceId: ${spring.application.name}:${random.value}
      ## this should not be enabled on production
      leaseRenewalIntervalInSeconds: 5      
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/